-- Xóa các cột cũ
ALTER TABLE users DROP COLUMN IF EXISTS elo_score;
ALTER TABLE users DROP COLUMN IF EXISTS total_matches;
ALTER TABLE users DROP COLUMN IF EXISTS win_rate;

-- Thêm các cột cho Đơn (Singles)
ALTER TABLE users ADD COLUMN IF NOT EXISTS elo_singles INTEGER DEFAULT 1000;
ALTER TABLE users ADD COLUMN IF NOT EXISTS matches_singles INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS win_rate_singles DECIMAL(5, 2) DEFAULT 0.0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS win_singles INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS loss_singles INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS streak_singles INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS max_streak_singles INTEGER DEFAULT 0;

-- Thêm các cột cho Đôi (Doubles)
ALTER TABLE users ADD COLUMN IF NOT EXISTS elo_doubles INTEGER DEFAULT 1000;
ALTER TABLE users ADD COLUMN IF NOT EXISTS matches_doubles INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS win_rate_doubles DECIMAL(5, 2) DEFAULT 0.0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS win_doubles INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS loss_doubles INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS streak_doubles INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS max_streak_doubles INTEGER DEFAULT 0;
